obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4]]
footprint_inflation: 0.01
#robot_radius: 0.175
inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: left_bump #scan right_bump
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
left_bump: {data_type: PointCloud2, topic: /rslidar_points, marking: true, clearing: true}
