local_costmap:
   global_frame: odom #odom
   robot_base_frame: base_link
   update_frequency: 1.0 #3.0
   publish_frequency: 1.0
   static_map: true #true
   rolling_window: true #false
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 1.0




